/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_globalload_LibraryLoaderJNI */

#ifndef _Included_com_globalload_LibraryLoaderJNI
#define _Included_com_globalload_LibraryLoaderJNI
#ifdef __cplusplus
extern "C"
{
#endif
  /*
 * Class:     com_globalload_LibraryLoaderJNI
 * Method:    test
 * Signature: ()V
 */
  JNIEXPORT void JNICALL Java_com_globalload_LibraryLoaderJNI_test(JNIEnv *, jobject);

  /*
 * Class:     com_globalload_LibraryLoaderJNI
 * Method:    loadLib
 * Signature: (Ljava/lang/String;)Z
 */
  JNIEXPORT jboolean JNICALL Java_com_globalload_LibraryLoaderJNI_loadLib(JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
